
version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile # Adjust this if your Dockerfile is in a different location
    environment:
      DB_URL: "host=postgres dbname=ecommerce_project user=postgres password=partner sslmode=disable"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: partner
    ports:
      - "5432:5432"

