// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ECOMMERCE_PROJECT/pkg/api"
	"github.com/ECOMMERCE_PROJECT/pkg/api/handlers"
	"github.com/ECOMMERCE_PROJECT/pkg/config"
	"github.com/ECOMMERCE_PROJECT/pkg/db"
	"github.com/ECOMMERCE_PROJECT/pkg/repository"
	"github.com/ECOMMERCE_PROJECT/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI1(configConfig config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handlers.NewUserHandelr(userUseCase)
	otpUseCase := usecase.NewOtpUseCase(configConfig)
	otpHandler := handlers.NewOtpHandler(configConfig, otpUseCase, userUseCase)
	adminRepository := repository.NewAdminRepository(gormDB)
	adminUsecase := usecase.NewAdminUsecase(adminRepository)
	adminHandler := handlers.NewAdminHandler(adminUsecase)
	serverHTTP := api.NewServerHTTP(userHandler, otpHandler, adminHandler)
	return serverHTTP, nil
}
