name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO111MODULE: "on"
  CGO_ENABLED: 0
  GOPROXY: "https://proxy.golang.org,direct"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3 

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy
          go mod verify

      - name: go fmt
        run: |
          go fmt ./...

      - name : Unit Tests
        run: |
          go test ./... -cover-

      - name: Build the Go application
        run: |
          mkdir -p build/bin
          go build -o build/bin/api ./cmd/api
